os: osx
osx_image: xcode14.1
language: objective-c
branches:
  only:
    - master

script:
  xcodebuild -project Jared.xcodeproj -scheme JaredTests test ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO